batch: 1
data: lfw
data_path: ./input/data
device: cpu
half: false
mode: defend
model: deepface
name: defend
num_classes: 1000
project: deepface
save_dir: ./output
selected_samples: 10
verbose: true
workers: 0
